# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

set -o vi
if [ -r $HOME/.tsi ]
then
  source $HOME/.tsi
fi

if [ -r $HOME/.tsp ]
then
  source $HOME/.tsp
fi

if [ -r $HOME/.tsp ]
then
  source $HOME/.db
fi

# Provide for backward compatability for older Boundary CLI
# python package
export BOUNDARY_EMAIL=$TSP_EMAIL
export BOUNDARY_API_TOKEN=$TSP_API_TOKEN
export BOUNDARY_API_HOST=$TSP_API_HOST

export APIHOST_PRE="api.truesight-staging.bmc.com"

alias creds='env | grep TSP'

export PATH=$HOME/bin:$PATH
